### ISSUE TITLE
Plot labels from examples unclear

### ISSUE THREAD

**Issue by lichadezhang** [suavecode/Tutorials#22]
Some graphs generated from the example code have unclear labels, see the attached image for an example
![Aerodynamic_Coefficients](https://user-images.githubusercontent.com/56762871/116650019-ad87b100-a9c3-11eb-907b-3d72e9a0ddad.png)

**Comment by planes** [comment]
Hi!
This is an issue with the current version of matplotlib and SUAVE. Matplotlib, the package that SUAVE uses to plot figures, just changed their routines. [You can see their writeup here](https://matplotlib.org/stable/users/whats_new.html#changes-to-behavior-of-axes-creation-methods-gca-add-axes-add-subplot).

The fix for this is simple. You can replace any line with this format
axes = fig.add_subplot(...

with
plt.subplot(....

If you have done a [develop install](https://suave.stanford.edu/download/develop_install.html), you should be able to just do a find and replace for the above in [this file](https://github.com/suavecode/SUAVE/blob/develop/trunk/SUAVE/Plots/Mission_Plots.py).

Another easy fix would be to change to matplotlib 3.3.4.

The next release of SUAVE will include these changes.
