### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'propulsors'

### ISSUE THREAD

**Issue by BBFlyer1** [suavecode/Tutorials#27]
I downloaded and installed SUAVE follow the Developer  instructions at https://suave.stanford.edu/download/standard_install.html and downloaded the tutorial
from Github at https://github.com/suavecode/SUAVE.  and the SUAVE tutorials from https://github.com/suavecode/Tutorials.  When I run either the tut_mission_B737.py or tut_solar_uav.py tutorial examples using Anaconda Spyder from the tutoral folder, I get The following Error:

runfile('E:/Users/Bob/Downloads/Suave/Tutorials-2.4.0/tut_mission_B737.py', wdir='E:/Users/Bob/Downloads/Suave/Tutorials-2.4.0')
Traceback (most recent call last):

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Core\Data.py", line 61, in __getattribute__
    return dictgetitem(self,k)

KeyError: 'propulsors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "E:\Users\Bob\Downloads\Suave\Tutorials-2.4.0\tut_mission_B737.py", line 947, in <module>
    main()

  File "E:\Users\Bob\Downloads\Suave\Tutorials-2.4.0\tut_mission_B737.py", line 48, in main
    configs, analyses = full_setup()

  File "E:\Users\Bob\Downloads\Suave\Tutorials-2.4.0\tut_mission_B737.py", line 83, in full_setup
    configs_analyses = analyses_setup(configs)

  File "E:\Users\Bob\Downloads\Suave\Tutorials-2.4.0\tut_mission_B737.py", line 108, in analyses_setup
    analysis = base_analysis(config)

  File "E:\Users\Bob\Downloads\Suave\Tutorials-2.4.0\tut_mission_B737.py", line 143, in base_analysis
    energy.network = vehicle.propulsors

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Core\Data.py", line 63, in __getattribute__
    return objgetattrib(self,k)

AttributeError: 'Config' object has no attribute 'propulsors' 

The tut_mission_B737.py code seems to setup a turbofan at line 402, but I can find nowhere in the example or in the SUAVE base code where this is assigned to 'propulsors.  

I am a relatively new python user, but the SUAVE egg seems to be properly loaded in to my E:\Users\Bob\anaconda3\Lib\site-packages folder SUAVE-2.4.0-py3.8.egg.

**Comment by RemyCharayron** [comment]
Hello,
I downloaded and installed SUAVE yesterday following the instructions and when I run any of the tutorials (in particular the tut_mission_B737.py), I get the same error as you:
AttributeError: 'Config' object has no attribute 'propulsors'

I found a solution that I am sharing with you now, but I am not sure that it is the right thing to do as I am a very beginner with the SUAVE code.
I replaced  line 143 : energy.network = vehicle.propulsors  
by: energy.network = vehicle.networks 
It seems to go well like that, but maybe one of the contributors can confirm this.

Good afternoon

**Comment by BBFlyer1** [comment]
I will give that a try.  Thanks. 

It appears this line of code is in most of the examples.  Wonder what was changed that made this not work?

**Comment by planes** [comment]
Hi folks. The issue has to version compatibility. The tutorials are only really guaranteed to work with the same numbered version of SUAVE. We do not update tutorials with every change in code that has not been released.

If you're using git, you can check out the master branch and that is equivalent.

We decided to remove propulsors as the default name in recognition of how complex the power systems are, so in future versions of SUAVE it will be named network.

**Comment by BBFlyer1** [comment]
Thanks for the response.

For those deeply involved in the development (and it is marvelous software) changes like this may seem trivial.  However, to someone new to SUAVE, discontinuities like this are devastating.  The user does not know if there is a software issue and installation issue or there is something wrong with how they are running the code.

Any time a major component changes it's name, like propulsors to networks, there should be a prominent display of this change, at least a caution note in the MD file.  In general, the old name should show up as depreciated when the new name is added, with a note in the depreciated message telling the new name and when the old method/function is going away.  For example: "propulsors' are depreciated in version 2.4.0 and replaced by networks.  Propulsors with be removed from the code in release 2.5.0."

Also, if the Tutorials are not in sync with the releases, or in sync with major releases only, that should be noted prominently on the tutorial page.  It would significantly improve the experience for the SUAVE user base.

Bob Bumpous
Boeing IT retired.

**Comment by planes** [comment]
Maybe my response was confusing.

The tutorial releases have matching version numbers to the SUAVE releases and are guaranteed to work together.

Bob, you indicated in your first post that you did a developer install. The developer installation guide at the beginning lists the master branch as the stable branch. If you choose not to use a stable branch, you should expect unstable results as you have found. You’re not using an official release. There are no notes because they’re still a work in progress. We just made this change days ago, that's how I know you're not using the master branch. That’s the cost of working on the bleeding edge. Sharp edges should be expected. This way of version controlling is standard practice with any open source project.

We understand that these changes are not trivial. They will be fully explained and documented in the next release when that happens.

I apologize that we don’t provide a heads up on deprecations. Road maps are fuzzier when software is developed by a small team of volunteers. Developers change things for their own personal needs, not from a paying customers road map. We’re in the midst of a major under the hood change to the networks and decided it was time for this nomenclature update. These changes are not complete yet and won't be until 2.5. When it comes most users will probably not realize that anything has change other than this.

We have already discussed internally a change prior to your posting. With the next release, it will no longer be possible to run the tutorials with anything other than same versioned released of SUAVE.

**Comment by BBFlyer1** [comment]
I apologize.  My mistake.  I went back and uninstalled the development library and tutorial and reinstalled the 2.4.0 SUAVE release and 2.4.0 Tutorial and things are working much better.  I have run both the tut_mission_B737.py and tut_concorde.py scripts and everything has worked correctly.

I think the work you and your team is doing is marvelous and want to thank you for all your hard work.
